#!/bin/sh

set -o errexit

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

set +o errexit

. "${GIT_ROOT}/make/include/versioning"

set -o errexit
set -o nounset

OSES="linux darwin"
GOARCH=${GOARCH:-$(go env GOARCH)}

for exe in stampy graphy; do
  for OS in ${OSES}; do
      GOOS="${OS}" go build \
	  -ldflags="-X main.version=${APP_VERSION}" \
	  -o "build/${OS}-${GOARCH}/${exe}" \
	  "./cmd/${exe}/"
  done
done
